"""initial schema

Revision ID: 27de10180dec
Revises: 
Create Date: 2026-02-04 14:31:22.800360
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '27de10180dec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_table('conversations',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active_dataset_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('user_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_created', 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_is_deleted'), 'conversations', ['is_deleted'], unique=False)
    op.create_index('ix_conversations_user', 'conversations', ['user_id'], unique=False)
    op.create_table('datasets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_format', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'ERROR', 'ARCHIVED', name='datasetstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('schema_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('profile_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('vector_namespace', sa.String(length=255), nullable=True),
    sa.Column('embedding_count', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.ARRAY(sa.String()), 'postgresql'), nullable=False),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('owner_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('updated_by', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_datasets_created', 'datasets', ['created_at'], unique=False)
    op.create_index(op.f('ix_datasets_created_at'), 'datasets', ['created_at'], unique=False)
    op.create_index(op.f('ix_datasets_is_deleted'), 'datasets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_datasets_owner_id'), 'datasets', ['owner_id'], unique=False)
    op.create_index('ix_datasets_owner_status', 'datasets', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_datasets_status'), 'datasets', ['status'], unique=False)
    op.create_table('analyses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('analysis_type', sa.Enum('EDA', 'STATISTICAL', 'ML_CLASSIFICATION', 'ML_REGRESSION', 'ML_CLUSTERING', 'TIME_SERIES', 'NLP', 'DEEP_LEARNING', 'CUSTOM', name='analysistype'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='analysisstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('insights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('visualizations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('agent_trace', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('owner_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('dataset_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('updated_by', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_analysis_type'), 'analyses', ['analysis_type'], unique=False)
    op.create_index('ix_analyses_created', 'analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyses_dataset_id'), 'analyses', ['dataset_id'], unique=False)
    op.create_index('ix_analyses_dataset_type', 'analyses', ['dataset_id', 'analysis_type'], unique=False)
    op.create_index(op.f('ix_analyses_is_deleted'), 'analyses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_analyses_owner_id'), 'analyses', ['owner_id'], unique=False)
    op.create_index('ix_analyses_owner_status', 'analyses', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_table('artifacts',
    sa.Column('artifact_type', sa.Enum('METRIC', 'TABLE', 'CHART', 'REPORT', name='artifacttype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manifest_path', sa.String(length=1024), nullable=False),
    sa.Column('data_path', sa.String(length=1024), nullable=True),
    sa.Column('preview', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dataset_version', sa.String(length=128), nullable=True),
    sa.Column('operator_name', sa.String(length=128), nullable=True),
    sa.Column('operator_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('owner_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('dataset_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('updated_by', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_artifact_type'), 'artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_artifacts_created_at'), 'artifacts', ['created_at'], unique=False)
    op.create_index('ix_artifacts_dataset_created', 'artifacts', ['dataset_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_artifacts_dataset_id'), 'artifacts', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_artifacts_is_deleted'), 'artifacts', ['is_deleted'], unique=False)
    op.create_index('ix_artifacts_owner_created', 'artifacts', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_artifacts_owner_id'), 'artifacts', ['owner_id'], unique=False)
    op.create_index('ix_artifacts_type_created', 'artifacts', ['artifact_type', 'created_at'], unique=False)
    op.create_table('data_adequacy_sessions',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('dataset_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('QUESTIONS', 'RUNNING', 'COMPLETED', 'FAILED', name='adequacysessionstatus'), nullable=False),
    sa.Column('state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_data_adequacy_sessions_created_at'), 'data_adequacy_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_adequacy_sessions_dataset_id'), 'data_adequacy_sessions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_data_adequacy_sessions_is_deleted'), 'data_adequacy_sessions', ['is_deleted'], unique=False)
    op.create_index('ix_data_adequacy_sessions_owner_created', 'data_adequacy_sessions', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_data_adequacy_sessions_owner_id'), 'data_adequacy_sessions', ['owner_id'], unique=False)
    op.create_index('ix_data_adequacy_sessions_owner_status', 'data_adequacy_sessions', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_data_adequacy_sessions_status'), 'data_adequacy_sessions', ['status'], unique=False)
    op.create_table('dataset_columns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('inferred_type', sa.String(length=50), nullable=False),
    sa.Column('semantic_type', sa.String(length=50), nullable=True),
    sa.Column('null_count', sa.Integer(), nullable=False),
    sa.Column('null_percentage', sa.Float(), nullable=False),
    sa.Column('unique_count', sa.Integer(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('mean_value', sa.Float(), nullable=True),
    sa.Column('median_value', sa.Float(), nullable=True),
    sa.Column('std_value', sa.Float(), nullable=True),
    sa.Column('distribution_type', sa.String(length=50), nullable=True),
    sa.Column('value_distribution', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('has_outliers', sa.Boolean(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('statistics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dataset_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'name', name='uq_dataset_column_name')
    )
    op.create_index(op.f('ix_dataset_columns_created_at'), 'dataset_columns', ['created_at'], unique=False)
    op.create_index('ix_dataset_columns_dataset', 'dataset_columns', ['dataset_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_type', sa.Enum('DATASET_PROCESSING', 'COMPUTE_PLAN', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('dataset_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_created', 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_dataset_id'), 'jobs', ['dataset_id'], unique=False)
    op.create_index('ix_jobs_dataset_type', 'jobs', ['dataset_id', 'job_type'], unique=False)
    op.create_index(op.f('ix_jobs_is_deleted'), 'jobs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_owner_id'), 'jobs', ['owner_id'], unique=False)
    op.create_index('ix_jobs_owner_status', 'jobs', ['owner_id', 'status'], unique=False)
    op.create_index('ix_jobs_owner_type', 'jobs', ['owner_id', 'job_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('agent_actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('conversation_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_table('ml_models',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.Enum('CLASSIFICATION', 'REGRESSION', 'CLUSTERING', 'FORECASTING', 'ANOMALY_DETECTION', 'NLP', 'RECOMMENDATION', 'CUSTOM', name='modeltype'), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('model_path', sa.String(length=1024), nullable=False),
    sa.Column('model_size_bytes', sa.Integer(), nullable=False),
    sa.Column('model_format', sa.String(length=50), nullable=False),
    sa.Column('hyperparameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('feature_names', sa.JSON().with_variant(postgresql.ARRAY(sa.String()), 'postgresql'), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('training_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('validation_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('test_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('feature_importance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_deployed', sa.Boolean(), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('training_duration_seconds', sa.Float(), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('updated_by', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ml_models_analysis', 'ml_models', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_ml_models_created_at'), 'ml_models', ['created_at'], unique=False)
    op.create_index(op.f('ix_ml_models_is_deleted'), 'ml_models', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ml_models_model_type'), 'ml_models', ['model_type'], unique=False)
    op.create_index('ix_ml_models_type_version', 'ml_models', ['model_type', 'version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ml_models_type_version', table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_model_type'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_is_deleted'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_created_at'), table_name='ml_models')
    op.drop_index('ix_ml_models_analysis', table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index('ix_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index('ix_jobs_owner_type', table_name='jobs')
    op.drop_index('ix_jobs_owner_status', table_name='jobs')
    op.drop_index(op.f('ix_jobs_owner_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_deleted'), table_name='jobs')
    op.drop_index('ix_jobs_dataset_type', table_name='jobs')
    op.drop_index(op.f('ix_jobs_dataset_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index('ix_jobs_created', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_dataset_columns_dataset', table_name='dataset_columns')
    op.drop_index(op.f('ix_dataset_columns_created_at'), table_name='dataset_columns')
    op.drop_table('dataset_columns')
    op.drop_index(op.f('ix_data_adequacy_sessions_status'), table_name='data_adequacy_sessions')
    op.drop_index('ix_data_adequacy_sessions_owner_status', table_name='data_adequacy_sessions')
    op.drop_index(op.f('ix_data_adequacy_sessions_owner_id'), table_name='data_adequacy_sessions')
    op.drop_index('ix_data_adequacy_sessions_owner_created', table_name='data_adequacy_sessions')
    op.drop_index(op.f('ix_data_adequacy_sessions_is_deleted'), table_name='data_adequacy_sessions')
    op.drop_index(op.f('ix_data_adequacy_sessions_dataset_id'), table_name='data_adequacy_sessions')
    op.drop_index(op.f('ix_data_adequacy_sessions_created_at'), table_name='data_adequacy_sessions')
    op.drop_table('data_adequacy_sessions')
    op.drop_index('ix_artifacts_type_created', table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_owner_id'), table_name='artifacts')
    op.drop_index('ix_artifacts_owner_created', table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_is_deleted'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_dataset_id'), table_name='artifacts')
    op.drop_index('ix_artifacts_dataset_created', table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_created_at'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_type'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index('ix_analyses_owner_status', table_name='analyses')
    op.drop_index(op.f('ix_analyses_owner_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_is_deleted'), table_name='analyses')
    op.drop_index('ix_analyses_dataset_type', table_name='analyses')
    op.drop_index(op.f('ix_analyses_dataset_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.drop_index('ix_analyses_created', table_name='analyses')
    op.drop_index(op.f('ix_analyses_analysis_type'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_datasets_status'), table_name='datasets')
    op.drop_index('ix_datasets_owner_status', table_name='datasets')
    op.drop_index(op.f('ix_datasets_owner_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_is_deleted'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_created_at'), table_name='datasets')
    op.drop_index('ix_datasets_created', table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('ix_conversations_user', table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_deleted'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index('ix_conversations_created', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
